version: '3'
services:
  rabbit:
    image: "rabbitmq:3"
    ports:
      - "5672:5672"
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  ms-save-user:
    build:
      context: MsSaveUserToDb
      dockerfile: DockerFile
    ports:
    - "8083:8083"
    depends_on:
      - mongodb
  ms-recive-user:
    build:
      context: MsReciveUserInfo
      dockerfile: DockerFile
    ports:
      - "8081:8081"
    depends_on:
      - rabbit
  ms-consume-and-transfer:
    build:
      context: MsConsumerAndTransfer
      dockerfile: DockerFile
    depends_on:
      - rabbit
      - ms-save-user
